# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone XS Max", # 6.5" required
  "iPhone XS", # 5.8 optional
  "iPhone 6s Plus", # 5.5" required
  "iPhone 6", # 4.7" optional
  "iPhone SE", # 4" optional if 5.5" provided
  "iPad Pro (12.9-inch) (3rd generation)", # required
  "iPad Pro (12.9-inch) (2nd generation)" # required
])

# languages([
#   "en-US",
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
# ])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
