platform :ios, '10.0'
project 'Finalsite'
#inhibit_all_warnings!
use_frameworks!

target 'Finalsite' do
  pod 'UICKeyChainStore'
  pod 'libPhoneNumber-iOS'
  pod 'DTFoundation'
  pod 'DTCoreText', :git => 'https://github.com/jasonelle/ios-pod-dtcoretext.git', :branch => 'jasonelle'
  pod 'JSCoreBom', '~> 1.1.1'
  pod 'SBJson', '~> 4.0.2'
#  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  pod 'NSHash'
  
  pod 'APAddressBook'
  
  # Networking
  pod 'Reachability'#, :git => 'https://github.com/jasonelle/ios-pod-reachability.git', :branch => 'jasonelle'
  pod 'SocketRocket'#, :git => 'https://github.com/jasonelle/ios-pod-socketrocket.git', :branch => 'jasonelle'
  pod 'AFNetworking'#, :git => 'https://github.com/jasonelle/ios-pod-afnetworking.git', :branch => 'jasonelle'
  pod 'TDOAuth'
  pod "AFOAuth2Manager"
  
  # Audio
  pod 'IQAudioRecorderController'
  pod 'FreeStreamer', :git => "https://github.com/muhku/FreeStreamer.git"
  
  # Views
  pod 'MBProgressHUD', '~> 1.0'
  
  pod 'TWMessageBarManager'
  
  pod 'SWTableViewCell', :git => 'https://github.com/finalsite/SWTableViewCell.git'

  pod 'SDWebImage', :git => 'https://github.com/jasonelle/ios-pod-sdwebimage.git'
  
  pod 'TTTAttributedLabel'
  pod 'BBBadgeBarButtonItem'
  
  pod 'REMenu'
  pod 'JDStatusBarNotification'
  pod 'HMSegmentedControl'
  pod "SWFrameButton"
  
  pod "NSGIF", "~> 1.0"
  pod 'INTULocationManager'
  pod "AHKActionSheet"
  
  pod "CYRTextView"
  
  pod 'SZTextView'
  
  pod 'DHSmartScreenshot'
  
  pod "RMDateSelectionViewController"
  
  pod 'PHFComposeBarView'
  pod 'DAKeyboardControl'

  pod 'MaterialComponents/ActivityIndicator'
  pod 'MaterialComponents/PageControl'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end
end
