platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'Jasonette' do

  # System
  pod 'UICKeyChainStore'
  pod 'libPhoneNumber-iOS'
  pod 'DTCoreText'
  pod 'JSCoreBom', '~> 1.1.1'
  pod 'SBJson', '~> 5.0.0'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']

  # Networking
  pod 'SocketRocket'
  pod 'AFNetworking'
  pod 'TDOAuth'
  pod "AFOAuth2Manager"

  # Audio
  pod 'IQAudioRecorderController'
  pod 'FreeStreamer', :git => "https://github.com/muhku/FreeStreamer.git"
  
  # Views
  pod 'MBProgressHUD', '~> 1.0'
  
  pod 'TWMessageBarManager'
  
  pod 'SWTableViewCell', :git => "https://github.com/gliechtenstein/SWTableViewCell.git"

  # TODO: Remove this dependency
  # change it to Contacts native api
  # https://github.com/Alterplay/APAddressBook/issues/138
  pod 'APAddressBook'
  
  
  pod 'TTTAttributedLabel'
  pod 'BBBadgeBarButtonItem'
  
  pod 'REMenu'
  pod 'JDStatusBarNotification' # $util.toast
  pod 'HMSegmentedControl'
  pod "SWFrameButton"
  
  pod "NSGIF", "~> 1.0"
  pod 'INTULocationManager'
  pod "AHKActionSheet"
  
  pod "CYRTextView"
  
  pod 'SDWebImage', :git => "https://github.com/rs/SDWebImage.git", :tag => '3.8.1'
  pod 'SZTextView'
  
  pod 'DHSmartScreenshot'
  pod 'NSHash'
  
  pod "RMDateSelectionViewController"
  
  pod 'PHFComposeBarView'
  pod 'DAKeyboardControl'
  
  #pod 'GoogleMobileAds', '~> 7.8'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end
end
