platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'Jasonette' do

  # System
  pod 'UICKeyChainStore', :git => 'https://github.com/jasonelle/ios-pod-uickeychainstore.git'
  pod 'libPhoneNumber-iOS'
  pod 'DTCoreText'
  pod 'JSCoreBom', '~> 1.1.1'
  pod 'SBJson', '~> 5.0.0'
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
  pod 'NSHash'
  
  ## TODO: Remove this dependency
  ## change it to Contacts native api
  ## https://github.com/Alterplay/APAddressBook/issues/138
  pod 'APAddressBook', :git => 'https://github.com/jasonelle/ios-pod-apaddressbook.git'
  
  # Networking
  pod 'SocketRocket'
  pod 'AFNetworking', :git => 'https://github.com/jasonelle/ios-pod-afnetworking.git'
  pod 'TDOAuth'
  pod 'AFOAuth2Manager'
  
  ## TODO: Update to latest version
  pod 'SDWebImage', :git => 'https://github.com/jasonelle/ios-pod-sdwebimage.git', :tag => '3.8.1'
  
  # Audio
  pod 'IQAudioRecorderController'
  pod 'FreeStreamer', :git => 'https://github.com/jasonelle/ios-pod-freestreamer.git'
  
  # Views
  pod 'MBProgressHUD', '~> 1.0'
  
  pod 'TWMessageBarManager'
  
  pod 'SWTableViewCell', :git => 'https://github.com/jasonelle/ios-pod-swtableviewcell.git'

  
  pod 'TTTAttributedLabel'
  pod 'BBBadgeBarButtonItem'
  
  pod 'REMenu'
  pod 'JDStatusBarNotification' # $util.toast
  pod 'HMSegmentedControl'
  pod 'SWFrameButton'
  
  pod 'NSGIF', '~> 1.0'
  pod 'INTULocationManager'
  pod 'AHKActionSheet'
  
  pod 'CYRTextView'
  
  pod 'SZTextView'
  
  pod 'DHSmartScreenshot'
  
  pod 'RMDateSelectionViewController'
  
  pod 'PHFComposeBarView'
  pod 'DAKeyboardControl'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end
end
